pool:
  name: MyAgentPool

variables:
  buildConfiguration: 'Release'

steps:
- bash: echo hello world

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'
